name: goalboard
services:
  frontend:
    build:
      context: frontend
      target: development
    volumes:
      - ./frontend/src:/code/src:ro
    networks:
      - client-side

  backend:
    build:
      context: backend
      target: development
    environment:
      - ADDRESS=0.0.0.0:8000
      - PG_DBNAME=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
    volumes:
      - ./backend:/code
    networks:
      - server-side
      - client-side
    depends_on:
      db:
        condition: service_healthy

  tests:
    image: golang:latest
    build:
      context: backend
      target: test
    volumes:
      - ./backend:/code
    working_dir: /code
    command: ENV=test go test ./UnitTesting -count=1
    networks:
      - server-side

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:80
    networks:
      - client-side
      - server-side
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-side
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    user: postgres

volumes:
  db-data: {}

networks:
  client-side: {}
  server-side: {}
